version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: meteo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meteo_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  streamlit:
    build: .
    container_name: meteo_streamlit
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - mysql
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app

volumes:
  db_data:
